spring.data.mongodb.uri=mongodb://localhost:27017/cloudshare

server.servlet.context-path=/api/v1.0

#spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=${Clerk.issuer}
clerk.jwks-url=${Clerk.jwks-url}
clerk.webhook.secret=${Clerk.webhook.secret}

#file upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

#razorpay configuration
razorpay.key.id=${razorpay.key.id}
razorpay.key.secret=${razorpay.key.secret}